name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.PAT_1 }}
          
          # User configuration
          user: ${{ github.repository_owner }}
          
          # Base metrics
          base: header, activity, community, repositories, metadata
          
          # Timezone
          config_timezone: Asia/Jakarta
          
          # IMPORTANT: Enable private mode untuk akses private commits & repos
          repositories: 200
          repositories_batch: 200
          repositories_forks: no
          repositories_affiliations: owner, collaborator, organization_member
          
          # Commits calendar (termasuk private commits)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Lines of code (termasuk private repos)
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          
          # Languages (termasuk private repos)
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          
          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          
          # Habits (coding hours, termasuk private)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          
          # Repositories traffic (private repos juga)
          plugin_traffic: yes
          
          # Follow-up of issues and pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_indepth: yes
          
          # Config display
          config_display: large
          config_output: svg
          config_padding: 6%, 10%
          
          # Optimization
          optimize: css, xml, svg
          experimental_features: --optimize-svg
