name: Simple Metrics
on:
  schedule: [{cron: "0 17 * * *"}] 
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Update GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          
          user: ${{ github.actor }}
          template: classic
          filename: metrics.svg
          config_timezone: Asia/Jakarta
          
          config_twemoji: yes
          config_animations: yes
          config_display: large
          config_background: "#0d1117"
          
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 1000
          plugin_lines_sections: base, charts
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css, dockerfile
